"""followers

Revision ID: 396f9fa66c0c
Revises: 4ab1189d74cd
Create Date: 2025-02-08 17:53:14.265110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396f9fa66c0c'
down_revision = '4ab1189d74cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
